softeerbootcamp-3rd/Team2-iFive

- BE/iDrop/src/main/java/ifive/idrop/config/CorsConfig.java
> feat: cors허용 도메인 추가

- BE/iDrop/src/main/java/ifive/idrop/config/CorsConfig.java
> feat: cors허용 도메인 변경

- BE/iDrop/src/main/java/ifive/idrop/config/WebConfig.java
- BE/iDrop/src/main/java/ifive/idrop/filter/CorsFilter.java
> feat: CorseFilter 구현

- BE/iDrop/src/main/java/ifive/idrop/config/WebConfig.java
- BE/iDrop/src/main/java/ifive/idrop/filter/CorsFilter.java
filter로직에서 설정한 origin이 매칭이 되어야 허용하도록 변경
> feat: filter를 통해 header의 origin을 필터링 하도록 수정

- FE/src/components/Search/AddressFinderMap/AddressFinderMap.jsx
- FE/src/components/Search/AddressFinderMap/initMap.js
- FE/src/constants/constants.js
- FE/src/hooks/useCoords.js
- FE/src/hooks/useMap.js
- FE/src/hooks/useMarker.js
- FE/src/utils/coords.js
> Feat#64 optimize map

- FE/src/App.jsx
- FE/src/pages/DriverDetail/DriverDetail.jsx
- FE/src/pages/DriverDetail/DriverDetail.module.scss
> feat: 기사 상세정보 퍼블리싱

- FE/src/service/api.js
> fix: login body key 변경

- FE/src/App.jsx
- FE/src/pages/SignUp/ParentSignUp.jsx
- FE/src/pages/SignUp/ParentSignUp.module.scss
> feat: 회원가입 페이지 퍼블리싱

- FE/src/components/Search/AddressFinderMap/AddressFinderMap.jsx
- FE/src/components/Search/Modal.jsx
- FE/src/pages/Search/Search.jsx
- FE/src/pages/Search/Search.module.scss
- FE/src/utils/search.js
> Feat#40 path

- BE/iDrop/src/main/java/ifive/idrop/dto/SubscribeRequest.java
- BE/iDrop/src/main/java/ifive/idrop/entity/enums/Days.java
- BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
정책 변경에 따라 변수이름 수정을 하였습니다.   
요일의 경우 MON, TUE... 에서 Mon, Tue와 같이 변경하였습니다.   
또한 dateRequest를 Schedule이라는 이름으로 변경하였습니다.
> Feat#50 subscribe

- FE/src/App.jsx
- FE/src/pages/Login/Login.jsx
- FE/src/utils/auth.js
> Feat#78 auth

- FE/src/App.jsx
> fix: import useRouteLoaderData

- FE/src/App.jsx
- FE/src/components/Search/AddressForm.jsx
- FE/src/components/Search/Modal.jsx
- FE/src/components/common/Footer/Footer.jsx
- FE/src/components/common/Footer/Footer.module.scss
- FE/src/pages/Confirmation/Confirmation.jsx
- FE/src/pages/DriverDetail/DriverDetail.jsx
- FE/src/pages/Login/Login.jsx
- FE/src/pages/Search/Search.jsx
- FE/src/utils/auth.js
> Feat#103 update search

- FE/src/App.jsx
- FE/src/components/Map/ParentMap.jsx
- FE/src/components/common/Bottomsheet/Bottomsheet.jsx
- FE/src/components/common/Bottomsheet/KidInfoBox.jsx
- FE/src/pages/Menu/Menu.jsx
- FE/src/pages/Menu/menuButton.jsx
- FE/src/service/api.js
> Feat#121 async request add

- BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
- BE/iDrop/src/main/java/ifive/idrop/repository/ParentRepository.java
- BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
- BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
service 클래스에서 사용하는 repository 클래스의 메소드 이름이 잘못되어 빌드 오류가 나던 것을 해결했습니다.
> fix: 빌드 오류 해결

- BE/iDrop/src/main/java/ifive/idrop/websocket/PickUpInfoRepository.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/WebSocketConfig.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/direction/Direction.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionFinder.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionResponse.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/location/CurrentPickUp.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
- BE/iDrop/src/main/resources/application.yml
- 네이버 경로찾기 api로 출발지~목적지 경로 조회
- 웹소켓 연결 직후 기사에게 경로 전송
resources/env 파일에 naver_api.yml 파일이 추가되어야합니다. 
해당 파일은 시크릿키가 포함되어 있어 슬랙 등 다른 채널로 안내드리겠습니다.
naver direction api를 사용하여 경로를 조회합니다.
호출하는 방법은 다음과 같습니다.
client id와 client secret을 세팅해줍니다. 이 정보는 외부로 유출되면 안되기에 naver_api.yml에 있는 것을 가져와서 사용합니다.
```java
headers.set("X-NCP-APIGW-API-KEY-ID", clientId);
headers.set("X-NCP-APIGW-API-KEY", clientSecret);
```
url을 생성합니다. 
아래 예시와 같이 query parameter를 사용합니다. start에는 출발지 위치, goal에는 도착지 위치를 넣어줍니다.
```text
https://naveropenapi.apigw.ntruss.com/map-direction/v1/driving?start=127.0295296, 37.5138649&goal=127.0316161, 37.51559
```
```java
StringBuilder sb = new StringBuilder(NAVER_DIRECTION_URL);
sb.append("?start=").append(start).append("&goal=").append(goal);
String url = sb.toString();
```
naver api 호출시 아래와 같은 …
> Feat#124 naver direction finder

- FE/src/App.jsx
- FE/src/components/Header/Header.jsx
- FE/src/components/Header/Header.module.scss
- FE/src/components/Modal/Modal.jsx
- FE/src/hooks/useFetch.js
- FE/src/pages/Menu/Menu.jsx
- FE/src/pages/Parents/History/History.jsx
- FE/src/pages/Parents/History/HistoryDetailModal/HistoryDetail.jsx
- FE/src/pages/Parents/History/HistoryDetailModal/HistoryDetail.module.scss
- FE/src/pages/Parents/History/HistoryItem/HistoryItem.jsx
- FE/src/pages/Parents/Subscription/DriverDetail/DriverDetail.jsx
- FE/src/pages/Parents/Subscription/DriverList/DriverList.jsx
- FE/src/service/mockdata.js
- FE/src/service/notification/foregroundMessage.js
- FE/src/service/notification/notificationAPI.js
- FE/src/service/notification/notificationPermission.js
> Feat#113 subscription history

- FE/.eslintignore
- FE/package.json
- FE/src/App.jsx
- FE/src/components/Footer/Footer.jsx
- FE/src/components/Header/Header.jsx
- FE/src/pages/Menu/Menu.jsx
- FE/src/pages/Parents/Profile/Profile.jsx
- FE/src/pages/Parents/Profile/Profile.module.scss
- FE/src/pages/Parents/Subscription/DriverDetail/DriverDetail.jsx
- FE/src/pages/Parents/Subscription/DriverDetail/DriverDetail.module.scss
- FE/src/pages/Parents/Subscription/DriverList/DriverList.module.scss
- FE/src/pages/Parents/Subscription/DriverList/DriverListItem/DriverListItem.jsx
- FE/src/pages/Parents/Subscription/Search/Search.jsx
- FE/yarn.lock
> Feat#33 parent profile

- BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
- BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
- BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
- BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
현재 진행 중인 픽업이 있는지 확인해주는 api 를 구현했습니다.
부모의 메인페이지에서 `실시간 픽업` 버튼 클릭 시 사용됩니다.
> feat: 부모의 현재 진행 중인 픽업 존재 여부 조회 api

- BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
히스토리 정보에 사진 확인시 목적지와 시작 주소를 표시할 수 있도록 변경
> feat: 히스토리에 시작, 목적지를 넣도록 변경

- BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
- BE/iDrop/src/main/java/ifive/idrop/filter/CorsFilter.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionFinder.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/direction/dto/Direction.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/direction/dto/NaverDirectionResponse.java
- BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
- BE/iDrop/src/main/resources/application.yml
네이버 경로 api 사용시 자동차 경로이다보니 출발지에서 연결되지 않습니다.
따라서 조회한 경로 맨 앞에 출발지의 주소를 넣어주었습니다.
> fix: 네이버 경로 맨앞에 출발지 추가

- FE/src/App.jsx
- FE/src/pages/Menu/MenuButton/MenuButton.jsx
실시간 픽업 중이 아닐 시 실시간 픽업 화면 접근 에러
> hotfix 에러 처리

- FE/package.json
- FE/src/pages/Parents/Subscription/Search/Search.jsx
- FE/yarn.lock
> 픽업 요일 추가/삭제 Toast 메시지 추가
